config/routes.rb
Rails.application.routes.draw do
  root "flights#index"

  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: :departure_airport_id
  has_many :arriving_flights, class_name: "Flight", foreign_key: :arrival_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  
  has_many :bookings
  has_many :passengers
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flight, only: [:new, :show]
  before_action :set_number_of_passengers, only: [:new, :show]

  def new
    @booking = Booking.new
    @number_of_passengers.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash[:notice] = "Your flight has successfully been booked. Your booking confirmation has been sent to your email!"
      @booking.passengers.each do |passenger|
        PassengerMailer.with(booking: @booking, passenger: passenger).booked_flight_confirmation_email.deliver
      end
      redirect_to booking_path(id: @booking.id, flight_id: @booking.flight_id)
    else
      flash[:notice] = "You must fill out all fields"
      @flight = Flight.find(params[:booking][:flight_id])
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, :number_of_passengers, passengers_attributes: [:name, :email])
  end

  def set_flight
    @flight = Flight.find(params[:flight_id])
  end

  def set_number_of_passengers
    @number_of_passengers = params[:number_of_passengers].to_i
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |a| [a.location, a.id] }
    @date_options = (Date.new(2022, 8, 1)..Date.new(2022, 8, -1)).map { |d| [d.strftime("%a, %b %d"), d] }
    @passenger_options = (1..4).map { |p| [p.to_s, p]}

    @flights = Flight.where("departure_airport_id = ? AND arrival_airport_id = ? AND departure_date = ?", params[:departure_airport_id], params[:arrival_airport_id], params[:departure_date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def params_present_and_no_flights_found?
    required = %i[departure_airport_id arrival_airport_id departure_date number_of_passengers]
    required.any? { |key| params.key?(key) } && @flights.empty?
  end
end

app/views/bookings/_full_flight_info.html.erb
<div class="mb-4 text-center">
  Flight Number : <%= @flight.flight_number %> | 
  Departs: <%= @flight.departure_airport.location %> | 
  Arrives: <%= @flight.arrival_airport.location %> | 
  Date: <%= @flight.departure_date.strftime("%A, %B %d") %>
  <br>
  Departure Time: <%= @flight.departure_time %> | 
  Duration: <%= @flight.flight_duration %>
</div>

app/views/bookings/_nested_booking_passenger_form.html.erb
<%= form_with model: @booking, data: { turbo: false }, url: bookings_path do |form| %>
  <%= form.fields_for :passengers do |passenger_form| %>
    <div class="input-group">
      <%= passenger_form.text_field :name, class: "form-control", placeholder: "Passenger Name" %>
      <%= passenger_form.email_field :email, class: "form-control", placeholder: "Passenger Email" %>
    </div>
    <br>
  <% end %>
  <%= form.hidden_field :flight_id, value: @flight.id %>
  <%= form.hidden_field :number_of_passengers, value: @number_of_passengers %>
  <div class="d-grid">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/bookings/_passenger_info.html.erb
<% @booking.passengers.each do |passenger| %>
  <%= "Name: #{passenger.name}" %> | 
  Seat: <%= "#{(65 + rand(20)).chr }#{rand(1..6)}" %>
  <br>
<% end %>

app/views/bookings/_short_flight_info.html.erb
<div class="mb-4">
  From: <%= @flight.departure_airport.location %> |
  To: <%= @flight.arrival_airport.location %> |
  Date: <%= @flight.departure_date.strftime("%A, %B %d") %> |
  Time: <%= @flight.departure_time %> |
  Flight Number : <%= @flight.flight_number %>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-danger text-center">
    <%= msg %>
  </div>
<% end %>
  
  <div class="text-center my-4">
    <h1 class="bubble-bit-font">Book your flight</h1>
  </div> 

<div class="card d-flex flex-column mx-auto mt-2" style="width: 57rem">
  <div class="card-body mx-auto">
    <%= render "short_flight_info"%>
    <%= render "nested_booking_passenger_form"%>
  </div>
</div>

app/views/bookings/show.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-success text-center">
    <%= msg %>
  </div>
<% end %>

<div class="text-center my-4">
  <h1 class="bubble-bit-font">Your Flight</h1>
</div>

<div class="card d-flex flex-column mx-auto mt-2" style="width: 53rem">
  <div class="card-body mx-auto">
    <%= render "full_flight_info" %>
    <h2 class="text-center bubble-bit-font">Passenger Info</h2>
    <%= render "passenger_info" %>
  </div>
</div>

app/views/flights/_results_selection_form.html.erb
<% if @flights.any? %>

  <div class="card d-flex flex-column mx-auto" style="width: 60rem">
    <div class="card-body mx-auto">
      <div class="text-center">
        <h1 class="bubble-bit-font">Available flights</h1>
      </div>
      <%= form_with model: @booking, data: { turbo: false }, url: new_booking_path, method: :get do |form| %>
        
        <% @flights.each do |flight| %>
          <div class="mb-4">
            <%= form.radio_button :flight_id, flight.id, required: true %>
            From: <%= flight.departure_airport.location %> |
            To: <%= flight.arrival_airport.location %> |
            Date: <%= flight.departure_date.strftime("%A, %B %d") %> |
            Time: <%= flight.departure_time %> |
            Flight Number : <%= flight.flight_number %>
            <%= form.hidden_field :number_of_passengers, value: params[:number_of_passengers] %>
          </div>
        <% end %>
        <div class="d-grid">
          <%= form.submit "Select Flight", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/flights/_search_form.html.erb
<div class="d-flex flex-column align-items-center my-4">
  <div class="text-center">
    <h1 class="bubble-bit-font">Find a flight!</h1>
  </div>
  <%= form_with model: @flight, data: { turbo: false }, method: :get do |form| %>
    <%= select_tag(:departure_airport_id, options_for_select(@airport_options), {:prompt => "Departing Airport"}) %>
    <%= select_tag(:arrival_airport_id, options_for_select(@airport_options), {:prompt => "Arriving Airport"}) %>
    <%= select_tag(:departure_date, options_for_select(@date_options), {:prompt => "Departure Date"}) %>
    <%= select_tag(:number_of_passengers, options_for_select(@passenger_options), {:prompt => "Passengers"}) %>
    <%= form.submit "Search flights", class: "search-button btn btn-primary" %>
  <% end %>
</div>

app/views/flights/index.html.erb
<% if params_present_and_no_flights_found? %>
  <p class="alert alert-danger">
    No flights found. Please make sure you have selected an option for each field.
  </p>
  <%= render "search_form" %>
<% elsif @flights.empty? %>
  <%= render "search_form" %>
  <%= image_tag("plane1.png", class: "plane1") %>
<% else %>
  <%= render "search_form" %>
  <%= render "results_selection_form" %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "8-bit flight booker", root_path, class: "navbar-brand mx-auto bubble-bit-font" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>8 Bit Flight Booker</title>
    <%= favicon_link_tag "plane1.png"%>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "styles.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>